create extension if not exists pgcrypto;

create table if not exists public.mental_quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  score integer not null,
  total_questions integer not null,
  rating integer not null check (rating between 1 and 5),
  would_use_feature boolean not null,
  requested_more boolean not null default false,
  review text not null default '',
  completed_at timestamptz not null default timezone('utc', now()),
  session_source text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.mental_quiz_answers (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.mental_quiz_sessions(id) on delete cascade,
  question_id integer not null,
  selected_answer text not null,
  correct_answer text not null,
  is_correct boolean not null,
  position text not null,
  difficulty integer not null,
  answered_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.mental_quiz_sessions enable row level security;
alter table public.mental_quiz_answers enable row level security;

drop policy if exists "anon_insert_mental_quiz_sessions" on public.mental_quiz_sessions;
create policy "anon_insert_mental_quiz_sessions"
on public.mental_quiz_sessions
for insert
to anon, authenticated
with check (true);

drop policy if exists "anon_insert_mental_quiz_answers" on public.mental_quiz_answers;
create policy "anon_insert_mental_quiz_answers"
on public.mental_quiz_answers
for insert
to anon, authenticated
with check (true);

create index if not exists mental_quiz_answers_session_id_idx
  on public.mental_quiz_answers(session_id);

create index if not exists mental_quiz_sessions_completed_at_idx
  on public.mental_quiz_sessions(completed_at desc);
