create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text,
  signed_up_at timestamptz not null default timezone('utc', now()),
  source text,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.waitlist enable row level security;

drop policy if exists "anon_select_waitlist" on public.waitlist;
create policy "anon_select_waitlist"
on public.waitlist
for select
to anon, authenticated
using (true);

drop policy if exists "anon_insert_waitlist" on public.waitlist;
create policy "anon_insert_waitlist"
on public.waitlist
for insert
to anon, authenticated
with check (true);

create unique index if not exists waitlist_email_unique_idx
  on public.waitlist (lower(email))
  where email is not null and btrim(email) <> '';
